Team-Invasores-of-Venezuela/invasionofvenezuelaP2

frontend-edunerd/src/app/docente/docente.component.html, frontend-edunerd/src/app/docente/docente.component.ts, frontend-edunerd/src/app/login/login.component.html, frontend-edunerd/src/app/login/login.component.ts, frontend-edunerd/tailwind.config.js
=> ED-42 mejora en diseño

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/CursoDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Curso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioProfesor.java
ED-50 Creacion de funciones CRUD para docente
ED-51 Creacion de funciones CRUD para cursos
ED-52 Creacion de funciones CRUD para estudiante
=> [ED-50, ED-51, ED-52] Funciones CRUD para Docente, Cursos y Estudiantes

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java
Se implementa una generacion automatica de usuarios, con sus respectivas validaciones, tanto a la manera de ingresar docentes por excel, como a la manera de ingresarlos de forma manual.
=> [ED-53] Manejo de usuarios 

frontend-edunerd/src/app/AuthService.ts, frontend-edunerd/src/app/app.routes.ts, frontend-edunerd/src/app/auth.guard.ts, frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.ts, frontend-edunerd/src/app/docente/docente.component.html, frontend-edunerd/src/app/docente/docente.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/login/login.component.html, frontend-edunerd/src/app/login/login.component.ts, frontend-edunerd/src/main.ts
ED-40: eliminar curso
ED-43: verificar si el usuario está logueado
ED-58: Agregar curso
=> [ED-40, ED-43, ED-58] Verificar usuario logueado, agregar cursos y eliminar curso

frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts, frontend-edunerd/src/app/login/login.component.html, frontend-edunerd/tailwind.config.js
A través de un formulario dentro de un modal, se puede agregar un estudiante manualmente, quedando guardado en la base de datos
=> [ED-44] Se añade la funcionalidad de agregar un estudiante de forma manual

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Usuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java
ED-53 Se agrego una clave foranea para relacionar los usuarios con los docentes respectivos.
ED-50, ED-51, ED-52 Se modificaron los endpoint para actualizar los datos de los modelos, manteniendo la consistencia de los datos ante actualizaciones reiterativas.
=> [ED-50, ED-51, ED-52, ED-53] Manejo Usuarios y CRUD

backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Curso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Estudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Profesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java
Se comenzo a modificar los modelos para adaptarlos al nuevo modelo de excel que recibira el backend y la base de datos
=> ED-87 modificacion de los modelos y archivos excel

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorSVC.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/CursoDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/CursoDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Curso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Estudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Profesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java
Basado en las indicaciones del profe para modificar los modelos, se arreglaron los CRUD de docente, estudiante y curso para reflejar de mejor manera estos cambios.
=> [ED-76, ED-77, ED-78] Actualizacion CRUD

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorSVC.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Estudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioProfesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java
solo se hicieron modificaciones menores para mezclar ambas ramas y mandar los cambios a pruebas
=> ED-87 se mezclaron los cambios de pruebas con la rama actual

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/AdministradorDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Estudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Usuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVC.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioUsuario.java
ED- 67 se arreglo bug que permitia ingresar varios docentes, cursos y alumnos "clones" si venian en el mismo excel
ED- 92 se agrego contadores para ver de forma resumida el puntaje de un determinado estudiante (se reutilizara el get de estudiante para acceder a estos contadores)
ED-94 se creo endpoint con su logica para crear un administrador
=> [ED-67,ED-92,ED-94] corrigiendo validaciones para los excel,adición de contadores a estudiantes y creacion de administradores

frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.ts, frontend-edunerd/src/app/docente-admin/docente-admin.component.html, frontend-edunerd/src/app/docente-admin/docente-admin.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts
+Se ajustaron los cambios del administrador para mostrar los nuevos datos de cursos, docente y estudiantes
+Se corrigió eliminar cursos aunque posteriormente fue comentado
=> [ED-61,ED-88,ED-89,ED-90] Modificar Formato tanto para creación de cursos-docente-estudiante

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorSVC.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/EstudianteDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioSVCOutput.java
Se crean los endpoint para generar archivos .xlsx de la informacion el base de datos de estudiantes, cursos y profesores.
=> [ED-79, ED-80, ED-81] Generacion archivos

frontend-edunerd/src/app/administrador/administrador.component.html, frontend-edunerd/src/app/app.component.ts, frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.ts, frontend-edunerd/src/app/docente/docente.component.html, frontend-edunerd/src/app/docente/docente.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts, frontend-edunerd/src/app/login/login.component.html, frontend-edunerd/src/app/login/login.component.ts, frontend-edunerd/src/main.ts, frontend-edunerd/tailwind.config.js
ED-47: Visualizar cursos
ED-66: modo claro/oscuro 
ED-70: redisponer cursoAdmin
ED-71: mensajes de confirmación de eliminación
=> [ED-47, ED-66, ED-70, ED-71] Visualizar cursos, modo claro/oscuro, redisponer cursoAdmin, mensajes de confirmación de eliminacion

frontend-edunerd/src/app/administrador/administrador.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.ts, frontend-edunerd/src/app/docente-admin/docente-admin.component.html, frontend-edunerd/src/app/docente-admin/docente-admin.component.ts, frontend-edunerd/src/app/docente/docente.component.html, frontend-edunerd/src/app/docente/docente.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts, frontend-edunerd/src/app/login/login.component.ts
ED-95: se agregó un botón para cambiar de modo claro/oscuro en cada interfaz
=> [ED-95] Modo claro/oscuro corregido

backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioCurso.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioEstudiante.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioProfesor.java
Se hizo un cambio al orden en el que las listas de estudiantes, cursos y docentes son enviadas al frontend. Ahora, el ultimo elemento añadido a la lista será el primero en visualizarse.
=> [ED-97, ED-98, ED-99] Orden listas

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorReporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/AdministradorDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ProfesorDTO2.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ReporteDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Profesor.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Reporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Usuario.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioReporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioReporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioUsuario.java
ED-106 se creo un modelo con su logica para Reporte
ED-107 se hizo un endpoint que recibe el reporte
ED-102  se agrego un atributo para imagenes para admins y profesores (falta implementar el editar foto de un usuario para cambiar las imagenes de un usuario ya creado, y por consiguiente, la de un profesor)
=> [ED-106,ED-107,ED-102] se creo modelo resporte, agrego atributo y mas

frontend-edunerd/src/app/administrador/administrador.component.html, frontend-edunerd/src/app/administrador/administrador.component.ts, frontend-edunerd/src/app/docente-admin/docente-admin.component.html, frontend-edunerd/src/app/docente-admin/docente-admin.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts
ED-101:  Actualización en componente estudiante-admin 
ED-104 :Actualización en componente docente-admin
ED-105: vista principal de administrador
=> [ED-101, ED-104, ED-105] Actualización en componente docente-admin y estudiante-admin y vista principal de administrador

frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.ts, frontend-edunerd/src/app/docente-admin/docente-admin.component.html, frontend-edunerd/src/app/docente-admin/docente-admin.component.ts, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.html, frontend-edunerd/src/app/estudiante-admin/estudiante-admin.component.ts
+Se arreglaron los problemas que tenía el componente de curso-admin
+Se agregó la funcionalidad para los componentes de curso/docente/estudiante de poder descargar sus datos en un excel
=> [ED-63, ED-64, ED-65, ED-103] Arreglando Curso-Admin y Agregando Desdardar datos de excel

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorUsuario.java, frontend-edunerd/src/app/administrador/administrador.component.html, frontend-edunerd/src/app/administrador/administrador.component.ts, frontend-edunerd/src/app/login/login.component.html, frontend-edunerd/src/app/login/login.component.ts
ED-100  se agrego un texto en rojo que avisa si hubo un error en el inicio de sesion
ED-96 cuando un admin ponga el mouse en su nombre, aparecen datos de su usuario
=> [ED-96,ED-100] retroalimentacion de intento de login y mostrar datos

frontend-edunerd/src/app/administrador/administrador.component.html, frontend-edunerd/src/app/curso-admin/curso-admin.component.html, frontend-edunerd/src/app/docente-admin/docente-admin.component.html
ED-101 se corrigió la vista del administrador
=> ED-101 corrección en vista de administrador

backend-edunerd/src/main/java/com/example/backend_edunerd/Controladores/ControladorReporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Dominio/ReporteDTO.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Modelos/Reporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Repositorios/RepositorioReporte.java, backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioReporte.java
Se crean 2 endpoint, uno que retorna toda la lista de reportes para facilitar la verificacion, y otro que entrega la lista de reportes para un usuario especifico.
=> [ED-109] Obtener Reportes por Matricula

backend-edunerd/src/main/java/com/example/backend_edunerd/Servicios/ServicioReporte.java
cada estudiante tiene asociado un contador negativo, y uno posito, lo que permite visualizar de forma mas agil cual es puntaje total (en cuanto a los reportes se refiere) que tiene cada alumno
=> ED-107 se agrego logica para aumentar los contadores
